### ISSUE TITLE
REQUEST_METHOD & REQUEST_URI

### ISSUE THREAD

**Issue by fenric** [sunrise-php/http-server-request#4]
Automatically assign `REQUEST_METHOD` & `REQUEST_URI` if they are not assigned to the method `Sunrise\Http\ServerRequest\ServerRequestFactory::createServerRequest()`.

**Comment by peter279k** [comment]
I think we can set the default value on `ServerRequestFactory::__construct`.

What do you think about this approach? @fenric.

**Comment by peter279k** [comment]
Hi @fenric, thank you for your reply and explanation.

And I found that the `REQUEST_METHOD` and `REQUEST_URI` are the key for `$_SERVER` global variable.

The `ServerRequestFactory::fromGlobals` exists on this global variable and perhaps we can assign the default values for these two keys.
